---
- hosts: all

  pre_tasks:
  - name: "check that certbot admin email is defined"
    fail:
      msg: "certbot admin email needs to be defined"
    when: admin_email is not defined

  - name: "check that email alias is provided for root user"
    fail:
      msg: "root email alias needs to be defined"
    when: root_email_alias is not defined

  - name: "check that forwarding email is defined"
    fail:
      msg: "forwarding email needs to be defined"
    when: forwarding_email is not defined

  roles:
    - initialize
    - mail-server
    - mail-alias-root-user
    - create-tls-certs
    - mail-server-add-tls-certs
    - mail-forwarding

