- name: preconfigure interactive settings for postfix - mailname
  debconf:
    name: postfix
    question: postfix/mailname
    vtype: string
    value: "{{ inventory_hostname }}"

- name: preconfigure interactive settings for postfix - main_mailer_type
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    vtype: string
    value: 'Internet Site'

- name: install mailutils
  apt:
    name: mailutils
    state: present

- name: "postfix configuration: inet interfaces = all ( default ) "
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces'
    line: inet_interfaces = all
  notify: restart postfix

- name: "postfix configuration: mydestination"
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^mydestination'
    line: mydestination = localhost.$mydomain, localhost, $myhostname
  notify: restart postfix

